# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.cache/wt} [current_project]
set_property parent.project_path {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/EX_MEM_regf.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/Hazard_detection.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/ID_EX_regf.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/IF_ID_regf.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/MEM_WB_regf.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/adder.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/alu.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/clock_divider_1.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/comparator.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/control.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/datamem.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/extender.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/forwarding.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/instmem.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/mux21.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/mux41.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/pipeline.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/reg.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/regfile.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/ring_counter.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/shifter.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/shifter2.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/ssd_driver.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/ssd_driver_modify.v}
  {E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/sources_1/new/pipeline_2.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/constrs_1/new/p2impl.xdc}}
set_property used_in_implementation false [get_files {{E:/2020 autumn/VE370/projects/project_2_pipeline_implementation_FPGA/project_2_pipeline_implementation_FPGA.srcs/constrs_1/new/p2impl.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top pipeline_implementation -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pipeline_implementation.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pipeline_implementation_utilization_synth.rpt -pb pipeline_implementation_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
